"""Print-resolution exports for figures that leave the notebook.

Inline notebook figures render at 120 DPI, which is right for reading on screen
and wrong for anything printed at A0. A poster panel is read from half a metre
and reproduced a metre wide, so a raster that looked crisp in Jupyter shows its
pixels on the board.

Each figure is written three ways because the destination decides which is
usable: PDF and SVG carry vectors, so text and lines stay sharp at any size and
a designer can restyle them in Illustrator or Inkscape; the 300 DPI PNG is the
fallback for tools that will not place vectors, and for pasting into slides.

Two deliberate choices. The vectors are transparent, so a panel takes the
poster's background rather than dropping a white rectangle onto it; the PNG is
not, because transparency in a raster surprises people at the print shop. And
``bbox_inches="tight"`` trims the surrounding whitespace matplotlib leaves,
which is otherwise the thing that makes a figure look small on a large board.

**Call this where the figure is built, not at the end of the notebook.** Cells
reuse the name ``fig``, and a figure is closed once it has been shown, so by the
last cell only the last figure is still reachable.

Output goes to ``reports/figures/poster/``, which is gitignored — these are
large, they are derived, and they are regenerated by re-running the notebook.
"""

from __future__ import annotations

from pathlib import Path
from typing import Callable

PROJECT_ROOT = Path(__file__).resolve().parents[2]
POSTER_FIG_DIR = PROJECT_ROOT / "reports" / "figures" / "poster"

#: Written for every figure. Vectors first — the PNG is a fallback.
FORMATS = ("pdf", "svg", "png")

#: Raster resolution. 300 DPI is the print-industry floor for photographic
#: quality; below it, text edges soften at poster size.
PNG_DPI = 300

#: Text enlargement applied before export. **One by default, deliberately.**
#:
#: The tempting fix for small figure labels is to enlarge them here, and it does
#: not work: a figure is a fixed number of inches wide, and doubling its type
#: makes subplot titles run into each other and tick labels overlap. Neither
#: ``tight_layout`` nor the constrained engine rescues it, because the text
#: genuinely does not fit any more.
#:
#: The lever that does work is the poster, not the figure. Legibility is
#:
#:     effective size = figure type size x (placed width / figure width)
#:
#: so a 641pt-wide figure carrying 10pt labels reads at 16pt in a 1,010pt
#: column and at 7.6pt in a 485pt one. Give a figure room and its own layout
#: survives intact; squeeze it and no amount of scaling here will save it.
#:
#: Raise this only for a single-panel figure with space to spare, where nothing
#: can collide.
POSTER_TEXT_SCALE = 1.0


def _restorer(legend, axes, x: float, y: float) -> Callable[[], None]:
    """Closure that puts one legend's anchor back where it was."""

    def restore() -> None:
        legend.set_bbox_to_anchor((x, y), transform=axes.transAxes)

    return restore


def _scale_legend_anchors(fig, scale: float) -> list[Callable[[], None]]:
    """Move legends anchored below their axes down, in step with the text.

    A legend placed with ``bbox_to_anchor=(x, -0.32)`` sits just under the tick
    labels, and that clearance was measured against the type size the figure was
    drawn at. Double the type and both the legend and the labels grow into each
    other; the layout engine will not intervene, because an explicit anchor is
    an instruction rather than a preference.

    So the anchor is scaled by the same factor as the text and put back
    afterwards. Only negative offsets are touched — those are the ones sitting
    outside the axes, where the collision happens.

    Returns callables that restore the original anchors.
    """
    undo: list[Callable[[], None]] = []
    if scale == 1.0:
        return undo
    for ax in fig.axes:
        legend = ax.get_legend()
        if legend is None:
            continue
        try:
            x0, y0, _, _ = legend.get_bbox_to_anchor()._bbox.bounds
        except AttributeError:  # a legend anchored some other way
            continue
        if y0 >= 0:
            continue
        legend.set_bbox_to_anchor((x0, y0 * scale), transform=ax.transAxes)
        undo.append(_restorer(legend, ax, x0, y0))
    return undo


def save_poster_fig(
    fig,
    name: str,
    directory: Path | None = None,
    text_scale: float = POSTER_TEXT_SCALE,
) -> list[Path]:
    """Write one figure as PDF, SVG and 300 DPI PNG. Returns the paths written.

    ``name`` becomes the filename stem and should say which notebook and which
    figure it is — ``nb04_fig1_exemplar_day`` — because these land in one flat
    directory and are chosen from there by a person building a poster.

    Text is enlarged by ``text_scale`` for the export and restored afterwards,
    so the figure still renders normally in the notebook. Pass ``1.0`` for a
    figure whose type sizes were already chosen for print.
    """
    directory = directory or POSTER_FIG_DIR
    directory.mkdir(parents=True, exist_ok=True)

    # Enlarge in place and put it back, so a notebook that shows the figure
    # after saving it does not suddenly render at poster type sizes.
    import matplotlib.text

    texts = fig.findobj(matplotlib.text.Text)
    original = [t.get_fontsize() for t in texts]
    if text_scale != 1.0:
        for t in texts:
            t.set_fontsize(t.get_fontsize() * text_scale)

    restore_anchors = _scale_legend_anchors(fig, text_scale)

    written = []
    for fmt in FORMATS:
        path = directory / f"{name}.{fmt}"
        # Vectors go transparent so the panel sits on the poster's own
        # background; the raster keeps a white one, which is what a print shop
        # expects to receive.
        fig.savefig(
            path,
            bbox_inches="tight",
            transparent=(fmt != "png"),
            **({"dpi": PNG_DPI} if fmt == "png" else {}),
        )
        written.append(path)

    for t, size in zip(texts, original):
        t.set_fontsize(size)
    for undo in restore_anchors:
        undo()
    return written
