"""Print-resolution exports for figures that leave the notebook.

Inline notebook figures render at 120 DPI, which is right for reading on screen
and wrong for anything printed at A0. A poster panel is read from half a metre
and reproduced a metre wide, so a raster that looked crisp in Jupyter shows its
pixels on the board.

Each figure is written three ways because the destination decides which is
usable: PDF and SVG carry vectors, so text and lines stay sharp at any size and
a designer can restyle them in Illustrator or Inkscape; the 300 DPI PNG is the
fallback for tools that will not place vectors, and for pasting into slides.

Two deliberate choices. The vectors are transparent, so a panel takes the
poster's background rather than dropping a white rectangle onto it; the PNG is
not, because transparency in a raster surprises people at the print shop. And
``bbox_inches="tight"`` trims the surrounding whitespace matplotlib leaves,
which is otherwise the thing that makes a figure look small on a large board.

**Call this where the figure is built, not at the end of the notebook.** Cells
reuse the name ``fig``, and a figure is closed once it has been shown, so by the
last cell only the last figure is still reachable.

Output goes to ``reports/figures/poster/``, which is gitignored — these are
large, they are derived, and they are regenerated by re-running the notebook.
"""

from __future__ import annotations

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
POSTER_FIG_DIR = PROJECT_ROOT / "reports" / "figures" / "poster"

#: Written for every figure. Vectors first — the PNG is a fallback.
FORMATS = ("pdf", "svg", "png")

#: Raster resolution. 300 DPI is the print-industry floor for photographic
#: quality; below it, text edges soften at poster size.
PNG_DPI = 300


def save_poster_fig(fig, name: str, directory: Path | None = None) -> list[Path]:
    """Write one figure as PDF, SVG and 300 DPI PNG. Returns the paths written.

    ``name`` becomes the filename stem and should say which notebook and which
    figure it is — ``nb04_fig1_exemplar_day`` — because these land in one flat
    directory and are chosen from there by a person building a poster.
    """
    directory = directory or POSTER_FIG_DIR
    directory.mkdir(parents=True, exist_ok=True)

    written = []
    for fmt in FORMATS:
        path = directory / f"{name}.{fmt}"
        # Vectors go transparent so the panel sits on the poster's own
        # background; the raster keeps a white one, which is what a print shop
        # expects to receive.
        fig.savefig(
            path,
            bbox_inches="tight",
            transparent=(fmt != "png"),
            **({"dpi": PNG_DPI} if fmt == "png" else {}),
        )
        written.append(path)
    return written
