"""Print-resolution exports for figures that leave the notebook.

Inline notebook figures render at 120 DPI, which is right for reading on screen
and wrong for anything printed at A0. A poster panel is read from half a metre
and reproduced a metre wide, so a raster that looked crisp in Jupyter shows its
pixels on the board.

Each figure is written three ways because the destination decides which is
usable: PDF and SVG carry vectors, so text and lines stay sharp at any size and
a designer can restyle them in Illustrator or Inkscape; the 300 DPI PNG is the
fallback for tools that will not place vectors, and for pasting into slides.

Two deliberate choices. The vectors are transparent, so a panel takes the
poster's background rather than dropping a white rectangle onto it; the PNG is
not, because transparency in a raster surprises people at the print shop. And
``bbox_inches="tight"`` trims the surrounding whitespace matplotlib leaves,
which is otherwise the thing that makes a figure look small on a large board.

**Call this where the figure is built, not at the end of the notebook.** Cells
reuse the name ``fig``, and a figure is closed once it has been shown, so by the
last cell only the last figure is still reachable.

Output goes to ``research/poster/exports/``, which is gitignored — these are
large, they are derived, and they are regenerated by re-running the notebook.
The subset the poster actually places is published into ``research/poster/assets``
by ``make poster``, and that subset is tracked; see ``research/poster/README.md``.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Callable

PROJECT_ROOT = next(
    p for p in Path(__file__).resolve().parents if (p / "pyproject.toml").exists()
)
POSTER_FIG_DIR = PROJECT_ROOT / "research" / "poster" / "exports"

#: Written for every figure. Vectors first — the PNG is a fallback.
FORMATS = ("pdf", "svg", "png")

#: Raster resolution. 300 DPI is the print-industry floor for photographic
#: quality; below it, text edges soften at poster size.
PNG_DPI = 300

#: Text enlargement applied before export. **One by default, deliberately.**
#:
#: The tempting fix for small figure labels is to enlarge them here, and it does
#: not work: a figure is a fixed number of inches wide, and doubling its type
#: makes subplot titles run into each other and tick labels overlap. Neither
#: ``tight_layout`` nor the constrained engine rescues it, because the text
#: genuinely does not fit any more.
#:
#: The lever that does work is the poster, not the figure. Legibility is
#:
#:     effective size = figure type size x (placed width / figure width)
#:
#: so a 641pt-wide figure carrying 10pt labels reads at 16pt in a 1,010pt
#: column and at 7.6pt in a 485pt one. Give a figure room and its own layout
#: survives intact; squeeze it and no amount of scaling here will save it.
#:
#: Raise this only for a single-panel figure with space to spare, where nothing
#: can collide.
POSTER_TEXT_SCALE = 1.0


#: Matches a notebook's own figure numbering at the head of an axes title —
#: "Figure 4 — fleet response by system state".
_FIGURE_PREFIX = re.compile(r"^\s*Figure\s+\d+\s*[—–-]\s*")


def _strip_figure_numbers(fig) -> list[tuple]:
    """Remove notebook figure numbers from axes titles, for the export only.

    A notebook numbers its figures in its own sequence, and a poster numbers
    them in reading order. Both are right and they disagree, so an exported
    panel titled "Figure 4" landing under a caption reading "Fig 5" is a
    contradiction the reader has to resolve. The poster's caption is the one
    that belongs to the poster, so the panel gives up its number.

    Returns (artist, original title) pairs for restoration.
    """
    original = []
    for ax in fig.axes:
        title = ax.get_title()
        if title and _FIGURE_PREFIX.match(title):
            original.append((ax, title))
            ax.set_title(_FIGURE_PREFIX.sub("", title))
    return original


def _restorer(legend, axes, x: float, y: float) -> Callable[[], None]:
    """Closure that puts one legend's anchor back where it was."""

    def restore() -> None:
        legend.set_bbox_to_anchor((x, y), transform=axes.transAxes)

    return restore


def _scale_legend_anchors(fig, scale: float) -> list[Callable[[], None]]:
    """Move legends anchored below their axes down, in step with the text.

    A legend placed with ``bbox_to_anchor=(x, -0.32)`` sits just under the tick
    labels, and that clearance was measured against the type size the figure was
    drawn at. Double the type and both the legend and the labels grow into each
    other; the layout engine will not intervene, because an explicit anchor is
    an instruction rather than a preference.

    So the anchor is scaled by the same factor as the text and put back
    afterwards. Only negative offsets are touched — those are the ones sitting
    outside the axes, where the collision happens.

    Returns callables that restore the original anchors.
    """
    undo: list[Callable[[], None]] = []
    if scale == 1.0:
        return undo
    for ax in fig.axes:
        legend = ax.get_legend()
        if legend is None:
            continue
        try:
            x0, y0, _, _ = legend.get_bbox_to_anchor()._bbox.bounds
        except AttributeError:  # a legend anchored some other way
            continue
        if y0 >= 0:
            continue
        legend.set_bbox_to_anchor((x0, y0 * scale), transform=ax.transAxes)
        undo.append(_restorer(legend, ax, x0, y0))
    return undo


def save_poster_fig(
    fig,
    name: str,
    directory: Path | None = None,
    text_scale: float = POSTER_TEXT_SCALE,
    strip_figure_numbers: bool = True,
) -> list[Path]:
    """Write one figure as PDF, SVG and 300 DPI PNG. Returns the paths written.

    ``name`` becomes the filename stem and should say which notebook and which
    figure it is — ``nb04_fig1_exemplar_day`` — because these land in one flat
    directory and are chosen from there by a person building a poster.

    Text is enlarged by ``text_scale`` for the export and restored afterwards,
    so the figure still renders normally in the notebook. Pass ``1.0`` for a
    figure whose type sizes were already chosen for print.

    ``strip_figure_numbers`` drops a leading "Figure N —" from axes titles, so
    the poster's numbering is the only one on the panel. Both restorations are
    undone before returning.
    """
    directory = directory or POSTER_FIG_DIR
    directory.mkdir(parents=True, exist_ok=True)

    # Enlarge in place and put it back, so a notebook that shows the figure
    # after saving it does not suddenly render at poster type sizes.
    import matplotlib.text

    texts = fig.findobj(matplotlib.text.Text)
    original = [t.get_fontsize() for t in texts]
    if text_scale != 1.0:
        for t in texts:
            t.set_fontsize(t.get_fontsize() * text_scale)

    restore_anchors = _scale_legend_anchors(fig, text_scale)
    restore_titles = _strip_figure_numbers(fig) if strip_figure_numbers else []

    written = []
    for fmt in FORMATS:
        path = directory / f"{name}.{fmt}"
        # Vectors go transparent so the panel sits on the poster's own
        # background; the raster keeps a white one, which is what a print shop
        # expects to receive.
        fig.savefig(
            path,
            bbox_inches="tight",
            transparent=(fmt != "png"),
            **({"dpi": PNG_DPI} if fmt == "png" else {}),
        )
        written.append(path)

    for t, size in zip(texts, original):
        t.set_fontsize(size)
    for undo in restore_anchors:
        undo()
    for ax, title in restore_titles:
        ax.set_title(title)
    return written


#: What the poster's QR code points a reader at. The live dashboard is the
#: landing page rather than the repository, because someone standing at a
#: poster has a phone and thirty seconds: a running dashboard rewards that,
#: a source tree does not. The repo is named in text beside the code for
#: anyone who wants it.
POSTER_QR_URL = "https://github.com/shaw029/power-trading"

#: Error correction level. QR spec levels are L/M/Q/H at roughly 7/15/25/30%
#: recoverable. A poster is read under glare, at an angle, sometimes creased
#: at the fold, so this takes the second-highest rather than the default.
QR_ERROR_CORRECTION = "Q"

#: Modules of quiet zone. The QR spec requires 4; less and scanners fail to
#: find the code against a busy background.
QR_BORDER = 4


def save_qr(
    url: str = POSTER_QR_URL,
    name: str = "repo_qr",
    directory: Path | None = None,
) -> list[Path]:
    """Write the poster's QR code as SVG and PNG. Returns the paths written.

    Kept in code rather than committed as an image so the encoded URL is
    reviewable — a QR on a printed poster is unreadable to its author, and a
    wrong one is discovered by a stranger with a phone, not by us.

    The SVG is what the poster places; the PNG is for slides. No PDF, because
    unlike the figures this is never opened in a vector editor.
    """
    import qrcode
    from qrcode.constants import (
        ERROR_CORRECT_H,
        ERROR_CORRECT_L,
        ERROR_CORRECT_M,
        ERROR_CORRECT_Q,
    )
    from qrcode.image.svg import SvgPathImage

    levels = {
        "L": ERROR_CORRECT_L,
        "M": ERROR_CORRECT_M,
        "Q": ERROR_CORRECT_Q,
        "H": ERROR_CORRECT_H,
    }
    directory = directory or POSTER_FIG_DIR
    directory.mkdir(parents=True, exist_ok=True)

    code = qrcode.QRCode(
        error_correction=levels[QR_ERROR_CORRECTION],
        border=QR_BORDER,
    )
    code.add_data(url)
    code.make(fit=True)

    written = []
    svg_path = directory / f"{name}.svg"
    code.make_image(image_factory=SvgPathImage).save(str(svg_path))
    written.append(svg_path)

    png_path = directory / f"{name}.png"
    # box_size is in pixels per module; 20 puts a typical 33-module code at
    # about 800px, enough for a slide without being a large file.
    code.make_image(fill_color="black", back_color="white").save(str(png_path))
    written.append(png_path)
    return written


#: Where a notebook's poster-facing numbers are written, alongside its figures.
POSTER_METRICS_DIR = POSTER_FIG_DIR


def save_poster_metrics(name: str, values: dict, directory: Path | None = None) -> Path:
    """Write one notebook's poster-facing numbers as JSON. Returns the path.

    **Why this exists.** A poster that repeats a number the notebook computed is
    a second copy, and the two drift the moment a window moves or a register
    refreshes — silently, because nothing checks a printed board against a
    notebook. Every figure on the poster should therefore be *read* from here,
    not retyped: ``poster.typ`` loads these files and substitutes the values, so
    re-running a notebook and rebuilding the poster cannot disagree.

    Values are pre-formatted strings, not raw floats. Rounding is an editorial
    decision that belongs with the analysis — the notebook knows a coverage
    share reads as "89%" and a cash figure as "£6.45m" — and Typst should not be
    reimplementing that.

    ``name`` should name the notebook, as the figures do: ``nb04``. Output lands
    in ``research/poster/exports/``, which is gitignored for the same reason the
    figures are: derived, and regenerated by re-running the notebook.
    """
    import json

    directory = directory or POSTER_METRICS_DIR
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{name}_metrics.json"
    path.write_text(json.dumps(values, indent=2, sort_keys=True) + "\n")
    return path
